name: Expo CI CD

on:
  push :
    branches : [release]

jobs:
  build-for-IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 21.x
      - uses: sinoru/actions-setup-xcode@v1.1.2
        with:
          xcode-version: '15.4'
          apple-id: ${{ secrets.APPLE_ID }}
          apple-id-password: ${{ secrets.APPLE_PASSWORD }}
      - name: Install deps
        run: yarn install && yarn add eas-cli
      - name: Load credentials
        run: echo ${{ secrets.CREDENTIALS_JSON_BASE64 }} | base64 -d > credentials.json
      - name: Build iOS app
        run: eas build -p ios --local
        env:
            EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
