name: Expo CI CD

on:
  workflow_dispatch:
  push:
    branches: 
      - 'release'    

jobs:
  build-for-IOS:
    environment: workflow-build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install xcode-install
        run: sudo gem install xcode-install
      - uses: sinoru/actions-setup-xcode@v1.1.2
        with:
          xcode-version: '15.4'
          apple-id: ${{ vars.APPLE_ID }}
          apple-id-password: ${{ vars.APPLE_PASSWORD }}
      - name: Install deps
        run: yarn install && yarn global add eas-cli
      - name: Patch rapi-ui
        run: sed -i '' 's/ios-close/close/g' node_modules/react-native-rapi-ui/components/Picker/Picker.tsx
      - name: Load credentials
        run: echo ${{ vars.CREDENTIALS_JSON_BASE64 }} | base64 -d > credentials.json
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ vars.EXPO_TOKEN }}
      - name: Build iOS app
        run: eas build -p ios --local --non-interactive --output build.ipa
        env:
            EXPO_TOKEN: ${{ vars.EXPO_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: /Users/runner/work/minichef/minichef/build.ipa
